tap "hashicorp/tap"
tap "osx-cross/arm", trusted: true
tap "osx-cross/avr", trusted: true
tap "oven-sh/bun"
tap "qmk/qmk", trusted: true
tap "steipete/tap"
tap "supabase/tap"

brew "actionlint"
brew "aws-sam-cli"
brew "awscli"
brew "clang-format"
brew "cmake"
brew "cocoapods"
brew "composer"
brew "fdupes"
brew "fzf"
brew "gh"
brew "git-delta"
brew "git-lfs"
brew "lazygit"
brew "libimobiledevice"
brew "lua"
brew "mecab"
brew "mecab-ipadic"
brew "mint"
brew "mkcert"
brew "neovim"
brew "oven-sh/bun/bun", trusted: true
brew "p7zip"
brew "periphery"
brew "pkgconf"
brew "poppler"
brew "python@3.14"
brew "qmk/qmk/qmk", trusted: true
brew "ripgrep"
brew "starship"
brew "supabase/tap/supabase", trusted: true
brew "swiftformat"
brew "swiftlint"
brew "tfenv"
brew "tmux"
brew "tree"
brew "typst"
brew "uv"
brew "watchman"
brew "xcodegen"
brew "zoxide"

cask "codex"
cask "codexbar"
cask "font-jetbrains-mono-nerd-font"
cask "karabiner-elements"
cask "ngrok"
cask "raycast"
cask "thaw"
cask "tuist"
cask "visual-studio-code"
cask "wezterm@nightly"
